# Generated by Django 5.0.6 on 2024-06-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headteacher', '0001_initial'),
        ('teacher', '0002_alter_student_student_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassDetails',
        ),
    ]
