# Generated by Django 5.0.6 on 2024-06-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headteacher', '0002_rename_class_classdetails'),
        ('teacher', '0002_alter_student_student_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassDetails',
            new_name='ClassDetail',
        ),
    ]
