# Generated by Django 5.0.6 on 2024-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headteacher', '0003_rename_classdetails_classdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
