# Generated by Django 5.0.6 on 2024-06-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headteacher', '0004_schoolyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=255)),
                ('term_year_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headteacher.schoolyear')),
            ],
        ),
    ]
